### ISSUE TITLE
[FEAT] Implement the first iteration of the "Predictions demo"

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#260]
This issue is tracking all issues of the first iteration. **Only use the low-level APIs for now**.  
BPMN Diagram: Pizza diagram from the examples provided by the BPMN specification.

We will provide 2 use cases

*   predicted late: vendor “Bake the pizza” in progress (started for 45 min for instance). Customer: predicted next task will be “Ask for pizza” after the complex gateway
*   predicted on time: vendor “Deliver pizza” in progress. Customer, predicted "received pizza" (we will highlight the whole path/branch)
*   Design: we use the same design as for the monitoring demo for legends, panels and tabs

We will work on the `master` branch. The demo will be publicly available in the live environment when the first iteration is completed.

```[tasklist]
### Tasks
- [x] #261
- [x] Improve the Pizza diagram for a better rendering.
- [x] 1st attempt in #264
- [x] 2nd attempt in #266
- [x] #263
- [x] Highlight running elements  #265
- [x] Highlight next predicted elements  #275
- [x] On predicted paths highlight: make non predicted path less visible #522
- [x] Restore message flow icons in the BPMN diagram once #524
- [x] bug in `bpmn-visualization` is fixed: https://github.com/process-analytics/bpmn-visualization-js/issues/1622
- [x] being able to style message flow icon precisely: https://github.com/process-analytics/bpmn-visualization-js/issues/928
- [x] Review CSS to use `rem` instead of `em` or `px` (may be use in the 'pulse' animation) #523
- [x] Add legends #525
- [x] Display the demo in the HTML home page for a public access #529
- [x] Replace the duplicated PathResolver, of Bonita day demo, by the new plugin / expertimental extension. See https://github.com/process-analytics/bpmn-visualization-examples/pull/515#discussion_r1243520414. -> We don't use it anymore.
- [x] deactive the navigation #527
- [x] reference the demo in the main README #529
- [x] Update the description in the HTML page #529
- [x] review the README of the demo #529
```
