### ISSUE TITLE
Clean the list of BPMN diagrams stored in this repository

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#356]
Originally, we created several BPMN Diagrams mainly to manually test the `bpmn-visualization` lib. Then, we introduced automatic visual tests and we don't use diagrams in the example repository for testing.
We have duplicated diagrams in the two repositories and the screenshots are no more up-to-date in the example repository.

**Tasks**

- [ ] decide what we expect from the diagrams in the examples repository: illustration, complex use case, other ?
  - [ ] introduce large and complex diagram to test performance? they be located in the lib repository instead
  - [ ] we currently have diagrams involving a single type of bpmn elements. Is it what we want here?
- [ ] remove diagrams fully available in the test of bpmn-visualization
- [ ] update screenshots for kept diagrams
- [ ] we have diagrams including artifacts that we currently not support (data input/output with markers for instance)
- [ ] diagrams including subprocess look interesting for testing
