### ISSUE TITLE
[INFRA] Automate the generation of the GitHub release draft 

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#375]
The creation of the release in the repository is currently fully manual.
It is described in https://github.com/process-analytics/bpmn-visualization-js/blob/v0.42.0/docs/contributors/maintainers.md#mark-the-bpmn-visualization-examples-repository-as-released

We could introduce a workflow that we could manually run. By passing the version value, we could generate a draft release with all information.
Maintainers would only have to review and clean the notes prior publishing the release.

Several actions exist to manage this. I have already used https://github.com/ncipollo/release-action.
We could do something like in https://github.com/bonitasoft/bonita-documentation-theme/blob/v1.11.0/.github/workflows/create-release.yml

As usual, prior implementing the workflow, don't forget to test it in https://github.com/process-analytics/github-actions-playground/

```[tasklist]
### Tasks
- [x] Test an implementation in the playground repository. https://github.com/process-analytics/github-actions-playground/pull/311#issuecomment-1880489125
- [x] Implementation in this repository  #584
- [x] Update the release documentation in the bpmn-visualization repository to run the new workflow (provide a direct link) and keep the manual procedure as a backup. See https://github.com/process-analytics/bpmn-visualization-js/pull/3011
```
