### ISSUE TITLE
[INFRA] Enforce usage of conventional commits for Pull Request titles

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#453]
**Rationale**: see https://github.com/orgs/process-analytics/projects/6/views/1?pane=info

### Tasks

- [x] create the GitHub workflow the enforce PR Title. It runs on `pull_request_target` to handle PR created by Dependabot and from fork repositories. It will be triggered once the PR introducing it is merged. See https://github.com/process-analytics/.github/pull/23#issuecomment-1332449120
- [x] update the GitHub workflows creating commits and pull requests. Also change the name of the created branches (infra to chore to match CC).
- [x] update the Dependabot configuration. Use an explicit configuration as by default, Dependabot use the commits in the repository which don't follow "conventional commits"
- [x] PR Template ~and/or contributing guide~
- [x] ~npm script (commit creation for release)~: not applicable in this repository
- [x] detect other impacts: search for string [ or ] in GitHub workflows, npm package, ...

See also https://github.com/process-analytics/github-actions-playground/issues/213 and https://github.com/process-analytics/github-actions-playground/issues/224
