### ISSUE TITLE
[FEAT] Implement various improvements for the Hacktoberfest demo

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#456]
**Is your feature request related to a problem? Please describe.**
Here is a list of improvements that have been identified when implementing the Hacktoberfest 2022 theme. See #374.
Feel free to create dedicated issues to split the list provided here.

### Tasks

- [x] If possible, improve the layout of the diagram: currently, we start left to right, and finish right to left which is not the usual way for the BPMN layout. #555
  - the width of the "registration task" can be decreased. There is no need to put the URL as it is not clickable
  - the exclusive gateway currently on the right of the 2nd line could be move to the first line. So we could draw an edge from the gateway at the end of the first line to the beginning of the 2nd line to continue the flow from left to right
  - don't display the url for registration (it is very long and is not clickable)
- [x] Update the demo description:  #561
  - [x] have less lines to reduce the need for scrolling. For instance: _Make it your own: change the project name to yours and share_
  - [x] review text margins

**Notes**: be aware of #540

**Comment by tbouffard** [comment]
All tasks are completed, so closing.
