### ISSUE TITLE
[FEAT] Reorganize the demo section in the HTML home page

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#545]
**Is your feature request related to a problem? Please describe.**

In the HTML home page, the demos are not stored in a specific order. They are added as they are added, following the existing list.

Demos provided by this repository are mixed with demos provided by external repositories.
Some demos are dedicated to a use case, others have been done for events and presentations and cover several topics.

https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.39.0/examples/index.html#demos

![home_0 39 0_02_annotated](https://github.com/process-analytics/bpmn-visualization-examples/assets/27200110/dd22dd36-16f4-46dd-b804-cf5a0335cb03)

**Describe the solution you'd like**
I suggest we better sort the demos to make this clearer for users.
We may introduce a dedicated sections for the demo done for an event.

```[tasklist]
### Tasks
- [ ] Decide of a new layout (this proposition can be totally rejected and the issue closed) with @csouchet 
- [ ] Update the page and add a new section if required
- [ ] Update the README to reflect the new organization
```

**Comment by csouchet** [comment]
### Some examples of propositions  
 

<table><tbody><tr><td><figure class="image"><img src="https://github.com/process-analytics/bpmn-visualization-examples/assets/4921914/db7ea41b-3059-4fff-b6a5-c7228a0cf239"></figure></td><td><figure class="image"><img src="https://github.com/process-analytics/bpmn-visualization-examples/assets/4921914/e3cd86dc-0de4-4178-903e-23031e9d5d80"></figure></td><td><figure class="image"><img src="https://github.com/process-analytics/bpmn-visualization-examples/assets/4921914/74915cda-4188-46ec-8448-b31ced7db511"></figure></td></tr></tbody></table>

**Comment by tbouffard** [comment]
I realized that the "external" bubble in my screenshot was confusing.
I added it not as an example of something that I had in mind but only to show where the external demos are currently placed 😢 

My proposal was to move them in a dedicated section or move them all to the end of the list.

That's being said, your proposals @csouchet are also great. I prefer the 2nd one as it is more discrete. I think we don't need to highlight a lot that the demo and the code are hosted externally, just pass the information.
We could hide an info icon on the right of the text to explain in a tooltip what it means.

**Comment by csouchet** [comment]
I just made some tests.   
Your proposition is ok for me too (even if I didn't understand it at the first time :slightly\_smiling\_face:).  
  
We should discuss in person the next week ^^
